## Exploring independent datasets

### Questions of interest:
- How is the data accessed (freely available or by special request, requires special status, etc.)?
- Data frequency (Daily/Monthly/Annually/Other)
- Data lag (e.g. data may be annual – but there may be a lag of 2 years before it is available)
- Are data “complete” when published or are there usually revisions after publication?
- If revised, how often and at what point are data “final”?
- Source of data (administrative records, sample survey, etc.)
- What portion of the population does this cover?  (not necessarily a specific percentage – but as an example, vehicle registration only covers those who own a vehicle and register it – so not a complete coverage of the population)
- Characteristics provided in the data (e.g. do the data provide demographic characteristics such as race, ethnicity, gender, age)?
- Other limitations
- General description
- Cost

## Voter Registration Data 
- [General Website and Current records](https://www.ncsbe.gov/results-data/voter-registration-data)
- [Historical snapshots](https://dl.ncsbe.gov/index.html?prefix=data/Snapshots/)

Reflections: 
- The data is freely accessible and free of cost. The source provides current voter-level registration records and snapshots of voter registration records across 15+ years.
- Current voter data is updated weekly, on Saturday mornings. Snapshots of voter registration records are annual and go back 10 years. They are taken on election day and on the first day of the year.
- There is no data lag but the website stated that after each election, it may take multiple days for all 100 counties to finalize their voter registration.
- There are 3-4 versions of the snapshot for each year. For a 'final' snapshot, can choose to use the latest, or the one closest to the date of the census count. 
- Data is sourced from National Voter Registration Act data and seems to be supplied directly by each county.
- These voter registration files contain the most up-to-date publicly available information for individuals registered or formerly registered to vote in North Carolina, as well as individuals who have attempted to register or have steps left uncompleted in the registration process. Formerly registered ('Removed') voters are omitted from the files if their most recent last-voted date is greater than 10 years.
- What's included in current data: Voter registration status (e.g., active, removed) and reason for status; voter demographics, party affiliation, and address; voter county, precinct, and district information (e.g., NC Senate and House, judicial); when applicable, county commissioner and additional local districts (e.g. sanitation, school). 
- What's included in historical data: Total number of active and inactive voters registered in North Carolina per election (at the time of the election), broken down by county, precinct, and voter demographics: party affiliation, race, ethnicity, and age. 
- Limitations: Historical data is relatively large to work with so computation will be hard initially. The 2020 snapshot has 30 million records. However, this shouldn't be a problem once we've aggregated the data by county. Missing data exists in some columns but I expect it to have a neglible impact in our research.

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#reading in current voter registration data for alamance county
voter_df= pd.read_table("../00_source_data/independent_datasets/ncvoter1_Alamance.txt" ,on_bad_lines='skip',encoding = 'unicode_escape') 
voter_df.head()

,county_id,county_desc,voter_reg_num,ncid,last_name,first_name,middle_name,name_suffix_lbl,status_cd,voter_status_desc,...,sanit_dist_abbrv,sanit_dist_desc,rescue_dist_abbrv,rescue_dist_desc,munic_dist_abbrv,munic_dist_desc,dist_1_abbrv,dist_1_desc,vtd_abbrv,vtd_desc
0,1,ALAMANCE,9005990,AA56273,AABEL,RUTH,EVELYN,NaN,A,ACTIVE,...,NaN,NaN,NaN,NaN,NaN,NaN,17.0,17TH PROSECUTORIAL,08N,08N
1,1,ALAMANCE,9178574,AA201627,AARDEN,JONI,AUTUMN,NaN,A,ACTIVE,...,NaN,NaN,NaN,NaN,MEB,MEBANE,17.0,17TH PROSECUTORIAL,10N,10N
2,1,ALAMANCE,9205561,AA216996,AARMSTRONG,TIMOTHY,DUANE,NaN,A,ACTIVE,...,NaN,NaN,NaN,NaN,NaN,NaN,17.0,17TH PROSECUTORIAL,103,103
3,1,ALAMANCE,9048723,AA98377,AARON,CHRISTINA,CASTAGNA,NaN,A,ACTIVE,...,NaN,NaN,NaN,NaN,BUR,BURLINGTON,17.0,17TH PROSECUTORIAL,03S,03S
4,1,ALAMANCE,9019674,AA69747,AARON,CLAUDIA,HAYDEN,NaN,A,ACTIVE,...,NaN,NaN,NaN,NaN,BUR,BURLINGTON,17.0,17TH PROSECUTORIAL,124,124

In [3]:
#no date variable - so this just gets updated with time
voter_df.columns

Index(['county_id', 'county_desc', 'voter_reg_num', 'ncid', 'last_name',
       'first_name', 'middle_name', 'name_suffix_lbl', 'status_cd',
       'voter_status_desc', 'reason_cd', 'voter_status_reason_desc',
       'res_street_address', 'res_city_desc', 'state_cd', 'zip_code',
       'mail_addr1', 'mail_addr2', 'mail_addr3', 'mail_addr4', 'mail_city',
       'mail_state', 'mail_zipcode', 'full_phone_number', 'confidential_ind',
       'registr_dt', 'race_code', 'ethnic_code', 'party_cd', 'gender_code',
       'birth_year', 'age_at_year_end', 'birth_state', 'drivers_lic',
       'precinct_abbrv', 'precinct_desc', 'municipality_abbrv',
       'municipality_desc', 'ward_abbrv', 'ward_desc', 'cong_dist_abbrv',
       'super_court_abbrv', 'judic_dist_abbrv', 'nc_senate_abbrv',
       'nc_house_abbrv', 'county_commiss_abbrv', 'county_commiss_desc',
       'township_abbrv', 'township_desc', 'school_dist_abbrv',
       'school_dist_desc', 'fire_dist_abbrv', 'fire_dist_desc',
       'water_dist_abbrv', 'water_dist_desc', 'sewer_dist_abbrv',
       'sewer_dist_desc', 'sanit_dist_abbrv', 'sanit_dist_desc',
       'rescue_dist_abbrv', 'rescue_dist_desc', 'munic_dist_abbrv',
       'munic_dist_desc', 'dist_1_abbrv', 'dist_1_desc', 'vtd_abbrv',
       'vtd_desc'],
      dtype='object')

In [4]:
voter_df.shape

(126564, 67)

In [5]:
(voter_df.isna().sum()/ voter_df.shape[0]).sort_values(ascending=False)[:30]

sanit_dist_abbrv        1.000000
township_desc           1.000000
county_commiss_desc     1.000000
county_commiss_abbrv    1.000000
ward_desc               1.000000
ward_abbrv              1.000000
school_dist_abbrv       1.000000
school_dist_desc        1.000000
fire_dist_abbrv         1.000000
fire_dist_desc          1.000000
water_dist_abbrv        1.000000
water_dist_desc         1.000000
sewer_dist_abbrv        1.000000
sewer_dist_desc         1.000000
township_abbrv          1.000000
rescue_dist_desc        1.000000
rescue_dist_abbrv       1.000000
sanit_dist_desc         1.000000
name_suffix_lbl         0.944020
mail_addr4              0.910520
mail_addr3              0.910448
mail_addr2              0.901030
municipality_abbrv      0.432832
munic_dist_desc         0.432832
munic_dist_abbrv        0.432832
municipality_desc       0.432832
full_phone_number       0.262436
birth_state             0.153938
nc_senate_abbrv         0.102802
nc_house_abbrv          0.102802
dtype: float64

In [6]:
# reading in the historical snapshot for first day of 2020
# I deleted this file from the repo so this line will no longer work
# histVoter_df= pd.read_table("../00_source_data/independent_datasets/VR_Snapshot_20200101.txt",encoding = 'unicode_escape') 
#histVoter_df.shape

NameError: name 'histVoter_df' is not defined

### SNAP Data Tables
[General Website](https://www.fns.usda.gov/pd/supplemental-nutrition-assistance-program-snap)

Reflections: 
- The data is freely accessible and free of cost. 
- The source provides Bi-Annual (January and July) State Project Area/County Level Participation and Issuance Data, starting 1989.
- Small data lag. The most recent dataset is from July 2021.
- No revisions to data. The July data can be considered final. For 2020, the report states that *"some data may still be revised after the publication of this report due to the specific reporting challenges faced during the public health emergency."*
- All data, except Treasury offset collection data was compiled from the National Data Bank, the official repository of SNAP data. Some of the data included in the recipient claims table is derived from administrative offset weekly statistical reports prepared by the U.S. Department of the Treasury.
- Data covers applicants and recipients of the SNAP program. Applicants are people who want to apply for SNAP benefits. Recipients are people who are currently receiving SNAP benefits and would like to find out more about the program.
- What's included: Public and Non public persons participation by county, Public and non public household participation by county, Public and non public benefits issued by county
- Limitations: I couldn't get a strict definition of what public vs non public means. Further I think SNAP participation would be affected by socioeconomic trends, and given that the counts of participation are relatively low, we can expect higher variance in these counts across years.

In [7]:
df_snap= pd.read_excel("../00_source_data/independent_datasets/Jul 2020.xlsx",header=3)
state= [str(x)[8:10] for x in df_snap["Substate/Region"]]
df_snap["state"]=state
df_snap=df_snap.loc[df_snap["state"]=='NC']
df_snap.shape

(100, 15)

In [8]:
df_snap.drop(['Unnamed: 2','Unnamed: 4','Unnamed: 6','Unnamed: 8','Unnamed: 10','Unnamed: 12'],axis=1,inplace=True)

In [ ]:
df_snap.head()

,Substate/Region,SNAP All Persons Public Assistance Participation,SNAP All Persons Non-Public Assistance Participation,Calc: SNAP Total PA and Non-PA People,SNAP All Households Public Assistance Participation,SNAP All Households Non-Public Assistance Participation,Calc: SNAP Total PA and Non-PA Households,SNAP All Total Actual PA & Non-PA Issuance,state
1518,3700102 NC EBT ALAMANCE CO DSS,364,24158,24522,142,11574,11716,2926149.0,NC
1519,3700302 NC EBT ALEXANDER,70,4230,4300,24,1979,2003,470344.0,NC
1520,3700501 NC EBT ALLEGHANY CO DSS,43,1456,1499,17,730,747,156349.0,NC
1521,3700701 NC EBT ANSON CO DSS,69,6037,6106,26,3236,3262,699361.0,NC
1522,3700902 NC EBT ASHE,87,3703,3790,37,1873,1910,397957.0,NC

In [9]:
np.var(df_snap['SNAP All Persons Public Assistance Participation'])

64703.63639999999

### Migration data
[General Website](https://www.irs.gov/statistics/soi-tax-stats-migration-data)

- The data is freely available and free of cost.
- The data is collected yearly between 1991 and 2020.
- Some data lag. The latest data available is from 2020.
- The data is usually not revised after publication. 
- Migration data for the United States are based on year-to-year address changes reported on individual income tax returns filed with the IRS. They present migration patterns by State or by county for the entire United States and are available for inflows—the number of new residents who moved to a State or county and where they migrated from, and outflows—the number of residents leaving a State or county and where they went. 
- The data used to produce migration data products come from individual income tax returns filed prior to late September of each calendar year and represent between 95 and 98 percent of total annual filings. However, since returns filed after September are not included, totals shown in migration data tables will not match analogous totals reported in other IRS statistical data products.
- For both outflows and inflows, the data includes Number of returns filed, which approximates the number of households that migrated, Number of personal exemptions claimed, which approximates the number of individuals, Total adjusted gross income, starting with Filing Year 1995, Aggregate migration flows at the State level, by the size of adjusted gross income (AGI) and age of the primary taxpayer.
- Those who are not required to file United States Federal income tax returns are not included in this file, and so the data under-represent the poor and the elderly.  Also excluded is the small percentage of tax returns filed after late September of the filing year.  Most taxpayers whose returns are filed after this date have been granted an extension to file by the IRS.  These taxpayers are likely to have complex returns that report relatively high income, and so the migration data set may under-represent the very wealthy, as well. The matching process also causes some returns to be excluded from the counts.  When the current-year tax return is compared to the prior-year tax return, only the Social Security Number of the primary taxpayer is considered.  If a secondary filer exists (as in the case of a married couple filing jointly), that Social Security Number is not recorded or compared in creating the migration dataset.  If, for example, a husband and wife file a joint return in the prior year, but divorce and file separately in the current year, only the husband’s current-year return will have a match with the prior-year return.  The now ex-wife’s current-year return becomes a non-match and will not be included in the data counts.  Other changes in filing status—from from joint to married filing separately—will also affect the data. The data is also in a format that makes it hard to work with. I modified an extract of it below to explore it.

In [12]:
migration_df= pd.read_csv("../00_source_data/independent_datasets/1920_nc_modified.csv")
migration_df.head()
#this data is just for inflows

,State Code,County Code,State Code.1,County Code.1,State,County Name,Number of returns,Number of individuals [1],Adjusted gross income (AGI)
0,37.0,1.0,96.0,0.0,NC,Alamance County Total Migration-US and Foreign,"4,957","9,533","256,490"
1,37.0,1.0,97.0,0.0,NC,Alamance County Total Migration-US,"4,957","9,533","256,490"
2,37.0,1.0,97.0,1.0,NC,Alamance County Total Migration-Same State,"3,567","6,881","179,953"
3,37.0,1.0,97.0,3.0,NC,Alamance County Total Migration-Different State,"1,390","2,652","76,537"
4,37.0,1.0,37.0,1.0,NC,Alamance County Non-migrants,"58,565","124,616","3,759,320"

In [13]:
migration_df.shape

(3501, 9)

In [14]:
migration_df.loc[migration_df["County Code"]==1.0]

,State Code,County Code,State Code.1,County Code.1,State,County Name,Number of returns,Number of individuals [1],Adjusted gross income (AGI)
0,37.0,1.0,96.0,0.0,NC,Alamance County Total Migration-US and Foreign,"4,957","9,533","256,490"
1,37.0,1.0,97.0,0.0,NC,Alamance County Total Migration-US,"4,957","9,533","256,490"
2,37.0,1.0,97.0,1.0,NC,Alamance County Total Migration-Same State,"3,567","6,881","179,953"
3,37.0,1.0,97.0,3.0,NC,Alamance County Total Migration-Different State,"1,390","2,652","76,537"
4,37.0,1.0,37.0,1.0,NC,Alamance County Non-migrants,"58,565","124,616","3,759,320"
5,37.0,1.0,37.0,81.0,NC,Guilford County,860,"1,708","48,379"
6,37.0,1.0,37.0,135.0,NC,Orange County,667,"1,305","32,021"
7,37.0,1.0,37.0,63.0,NC,Durham County,649,"1,269","30,168"
8,37.0,1.0,37.0,183.0,NC,Wake County,338,628,"17,447"
9,37.0,1.0,37.0,33.0,NC,Caswell County,104,217,"3,636"
10,37.0,1.0,37.0,37.0,NC,Chatham County,95,181,"4,927"
11,37.0,1.0,37.0,67.0,NC,Forsyth County,80,133,"4,777"
12,37.0,1.0,37.0,151.0,NC,Randolph County,79,149,"3,524"
13,37.0,1.0,37.0,119.0,NC,Mecklenburg County,71,132,"5,424"
14,37.0,1.0,37.0,157.0,NC,Rockingham County,67,132,"3,109"
15,37.0,1.0,37.0,145.0,NC,Person County,48,99,"1,784"
16,37.0,1.0,37.0,51.0,NC,Cumberland County,37,74,"2,029"
17,37.0,1.0,37.0,77.0,NC,Granville County,36,58,"1,547"
18,37.0,1.0,37.0,129.0,NC,New Hanover County,36,68,"1,749"
19,37.0,1.0,37.0,101.0,NC,Johnston County,26,55,"1,348"
20,37.0,1.0,37.0,147.0,NC,Pitt County,24,39,"1,157"
21,37.0,1.0,37.0,57.0,NC,Davidson County,23,36,472
22,37.0,1.0,37.0,19.0,NC,Brunswick County,20,30,"1,199"
23,37.0,1.0,58.0,0.0,SS,Other flows - Same State,307,568,"15,257"
24,37.0,1.0,59.0,0.0,DS,Other flows - Different State,"1,390","2,652","76,537"
25,37.0,1.0,59.0,1.0,DS,Other flows - Northeast,293,541,"16,996"
26,37.0,1.0,59.0,3.0,DS,Other flows - Midwest,158,285,"6,213"
27,37.0,1.0,59.0,5.0,DS,Other flows - South,762,"1,454","39,646"
28,37.0,1.0,59.0,7.0,DS,Other flows - West,177,372,"13,682"
29,37.0,1.0,57.0,9.0,FR,Foreign - Other flows,d,d,d

In [ ]:
#we can use inflows and outflows to calculate net migration